site:
  title: Baltimore NodeSchool
  links:
    github: https://github.com/nodeschool/baltimore
    twitter: http://twitter.com/bmorenodeschool
  events:
    -
      start: 2016-06-12T13:00:00-04:00
      end: 2016-06-12T17:00:00-04:00
      registerLink: https://ti.to/baltimorenodeschool/seven
      location:
        name: Betamore
        link: https://betamore.com
      workshops: ["Learn You Node", "Javascripting", "Stream Adventure"]
      sponsors:
        - charmCityJS
        - Betamore
        - Asymmetrik
    -
      start: 2016-08-13T13:00:00-04:00
      end: 2016-08-13T17:00:00-04:00
      location:
        name: Betamore
        link: https://betamore.com
    -
      start: 2016-10-09T13:00:00-04:00
      end: 2016-10-09T17:00:00-04:00
      location:
        name: Betamore
        link: https://betamore.com
    -
      start: 2016-12-10T13:00:00-05:00
      end: 2016-12-10T17:00:00-05:00
      location:
        name: Betamore
        link: https://betamore.com

workshops:
  -
    name: Learn You Node
    description: for learning node
    link: https://github.com/workshopper/learnyounode
  -
    name: Javascripting
    description: for those interested in learning JavaScript itself
    link: https://github.com/sethvincent/javascripting
  -
    name: Stream Adventure
    description: for a more advanced lesson
    link: https://github.com/substack/stream-adventure
  -
    name: Browserify Adventure
    description: if you want to experiment with npm + browsers
    link: https://github.com/substack/browserify-adventure

sponsors:
  -
    name: charmCityJS
    link: http://charmcityjs.com
  -
    name: Betamore
    link: https://betamore.com
  -
    name: Asymmetrik
    link: http://asymmetrik.com
