site:
  title: Baltimore NodeSchool
  links:
    github: https://github.com/nodeschool/baltimore
    twitter: http://twitter.com/charmcityjs
  events:
    -
      start: 2018-02-10T13:00:00-05:00
      end: 2018-02-10T17:00:00-05:00
      registerLink: https://ti.to/baltimorenodeschool/fourteen
      location:
        name: Betamore City Garage
        link: http://www.citygarage.vc/
      workshops: ["Special Topic", "Learn You Node", "Javascripting", "Advanced Topics"]
      sponsors:
        - charmCityJS
        - Betamore

    -
      start: 2018-05-06T13:00:00-04:00
      end: 2018-05-06T17:00:00-04:00
      location:
        name: Betamore City Garage
        link: https://betamore.com

    -
      start: 2018-08-19T13:00:00-04:00
      end: 2018-08-19T17:00:00-04:00
      location:
        name: Betamore City Garage
        link: https://betamore.com

    -
      start: 2018-11-10T13:00:00-05:00
      end: 2018-11-10T17:00:00-05:00
      location:
        name: Betamore City Garage
        link: https://betamore.com

workshops:
  -
    name: Special Topic
    description: Each NodeSchool we offer a different "Special Focus" class that targets an advanced topic for everyone to learn together.  Our February Special Focus is going to be <b>ES6</b>, an introduction to all of the spify new features that ES6 (ECMAScript 6, ES2015) introduced to the JavaScript languages. We've had a lot of requests for this topic, so we finally decided to give it some good coverage. Very exciting stuff!
    link: https://github.com/yosuke-furukawa/tower-of-babel

  -
    name: Learn You Node
    description: An introduction into NodeJS and all the really cool things you can do with JavaScript outside of the browser! A basic understanding of JavaScript is recommended.
    link: https://github.com/workshopper/learnyounode

  -
    name: Javascripting
    description: A great place to start if you don't know any JavaScript and want to learn this amazing language.
    link: https://github.com/sethvincent/javascripting

  -
    name: Advanced Topics
    description: Explore any of the other adanced NodeSchool topics like Stream-Adventures, WebGL, Web Audio, Browserify, etc. If there's a NodeSchool lesson, we will help you with it.
    link: http://nodeschool.io/#workshoppers

sponsors:
  -
    name: charmCityJS
    link: http://charmcityjs.com
  -
    name: Betamore
    link: https://betamore.com
